#!/bin/sh
### BEGIN INIT INFO
# Provides:          minecraft
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Minecraft Server
# Description:       Manages the Minecraft server
### END INIT INFO

MINECRAFT_USER="$USER"
MINECRAFT_HOME="/home/minecraft/server"
SERVER_SCRIPT="run-minecraft.sh"
SCREEN_NAME="minecraft"
PIDFILE="/var/run/${SCREEN_NAME}.pid"

case "$1" in
  start)
    echo "Starting Minecraft server"
    start-stop-daemon --start --quiet \
      --pidfile "$PIDFILE" \
      --make-pidfile \
      --chuid "$MINECRAFT_USER" \
      --chdir "$MINECRAFT_HOME" \
      --startas /usr/bin/screen -- \
      -DmS "$SCREEN_NAME" ./$SERVER_SCRIPT
    ;;
  stop)
    echo "Stopping Minecraft server"
    su - "$MINECRAFT_USER" -c "screen -S $SCREEN_NAME -p 0 -X stuff 'stop$(printf '\r')'"
    sleep 5
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE"
    ;;
  restart)
    $0 stop
    sleep 2
    $0 start
    ;;
  status)
    if [ -f "$PIDFILE" ] && kill -0 "$(cat $PIDFILE)" >/dev/null 2>&1; then
      echo "Running"
      exit 0
    else
      echo "Stopped"
      exit 1
    fi
    ;;
  console)
    exec su - "$MINECRAFT_USER" -c "screen -r $SCREEN_NAME"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status|console}"
    exit 2
    ;;
esac

exit 0